### ISSUE TITLE
Stereo WAV problem: only the left channel is rendered

### ISSUE THREAD

**Issue by The-Beesh-Spweesh** [Zeinok/OVGen#1]
Whenever you want to load a stereo WAV file through OVG, the scope will only show its left channel. In SidWiz 2, the scope will mix both the left and right channels simultaneously so that it will show both channels.

**Comment by Zeinok** [comment]
fixed.

https://github.com/Zeinok/OVG/commit/b0546071aafd8a5e96b9e09803e707400eae964d
