### ISSUE TITLE
Can't use same WAV file for multiple channel slots, or cannot use 24-bit / 32-bit float WAV

### ISSUE THREAD

**Issue by The-Beesh-Spweesh** [Zeinok/OVGen#3]
This is also the same bug in SidWiz 2 since its v2rj_13 update, where a single WAV file in multiple slots caused an error after the OK button was pressed on the codec selection window. You cannot load a 24-bit or 32-bit WAV stream either, as it causes the waves to not render at all, and the master audio to have a glitch in VLC Media Player.

One suggestion apart from this issue topic is to make the line thickness, middle line, and background color configurable for each channel.

**Comment by OPNA2608** [comment]
Please open multiple issues for multiple problems instead of one issue for many problems.
