### ISSUE TITLE
Deleting x86 binaries was a bad decision from you and OPNA2608

### ISSUE THREAD

**Issue by StinkerB06** [Zeinok/OVGen#4]
In honesty, why on earth would you take down the x86 (32-bit) binaries? That was a really dumb decision. I apologize for posting about those fantasy consoles only being available for x64 platforms.

**Comment by Zeinok** [comment]
Yes I admit that I deleted 32-bit build is dumb and I was just being a jerk, you don't really need to apologize for your postings.

But also the market share of 32-bit is low according to [Steam's hardware/software survey](http://store.steampowered.com/hwsurvey), I don't see there is any need to build a 32-bit binary.
You could compile it by yourself if you really need it.
