### ISSUE TITLE
Bad Header error

### ISSUE THREAD

**Issue by matvtssf** [Zeinok/OVGen#5]
Getting some bad Header errors when loading WAV files from adobe audition.

"Bad Header '20', expected '16'" is the error I get on all files saved from adobe audition.

**Comment by Zeinok** [comment]
Make sure your wav file is in 16-bit depth or 8-bit depth.

If you exported with those bitdepth above and doesn't work, upload the wav file for me to check out the header, thanks.

**Comment by matvtssf** [comment]
They were 16-bit for sure. Here's an example WAV file (also including a video of the saving process in case that helps :) )

EDIT: video had no sound, but I redid it to show resaving file in audacity fixes it (maybe Adobe Audition is corrupting the header, because audacity seems to think it's 32-bit floating point when the WAV file is opened)

[rufustest2.zip](https://github.com/Zeinok/OVGen/files/2120319/rufustest2.zip)

**Comment by Zeinok** [comment]
fixed
There is a field named `ExtraParams`, and normally it should not appear in PCM-encoded file, as it documented [here](http://soundfile.sapp.org/doc/WaveFormat/), but I still fixed it if these problem still occure in future.
https://github.com/Zeinok/OVGen/commit/061782a4f8272b5e91ab24cae782b8441166ce51

**Comment by Zeinok** [comment]
https://github.com/Zeinok/OVGen/releases/tag/0.0.17.3
Released.
Try if you can use the wav file exported from Adobe Audition.

**Comment by matvtssf** [comment]
Works like a charm now thank you! :)

**Comment by The-Beesh-Spweesh** [comment]
I also get "Bad Header '40'" for other WAV files I load into the program. Some file-conversion websites put this value in the header.

**Comment by Zeinok** [comment]
Please open a new issue, thanks.
