### ISSUE TITLE
Oscilloscope view is electronically slow

### ISSUE THREAD

**Issue by SgtPepperArc360** [Zeinok/OVGen#6]
Hello, this is SgtPepperArc360.
I've recently joined GitHub today and need to address a major problem I'm having.

I was just making an oscilloscope view of one of my musical compositions and after encoding each channel to a 44100Hz 16-bit WAV file, I loaded them up and then imported the master audio file. However, after the video renders... **the waveforms are relatively slower!**

No, there is _absolutely_ nothing I can do about it. **HELP!**

**Comment by 0x5066** [comment]
What do you mean _**electronically slow**_?
How about you deliver us your video files, yes?

**Comment by Zeinok** [comment]
I have several questions:
1. Are you using latest FFmpeg release? And what version?
2. Have you changed your FFmpeg commandline?
3. Are you using the latest OVGen release?

**Comment by SgtPepperArc360** [comment]
Oh, wait a second. I forgot it was Audacity I had to blame, not OVGen. Never mind*.

*= I'm not closing this issue _yet_, I just need to confirm whether or not I was doing the right thing.
I mentioned Audacity because I was using it to convert the 32-bit float WAV files to 16-bit PCM WAV files.

**Comment by 0x5066** [comment]
### **How about you deliver us your video files, yes?**

**Comment by SgtPepperArc360** [comment]
@The1Freeman 
Sorry, I can't! The video is an MP4 file and when I tried to import it, it told me the format wasn't supported!

**Comment by SgtPepperArc360** [comment]
You know what?! **Forget it.**

**Comment by Zeinok** [comment]
Did the problem disappeared?
You could upload it to Google Drive, YouTube, Dropbox, MEGA, or somewhere you can upload your video, so we can investigate into this problem, If you would like, please give us your OVGen config file ,OVGen version, FFmpeg version.

If you tried to fix it by yourself but doesn't work and you really want to forget it, you could try SidWiz2 by RushJet1.
